version: '3.8'

services:
  carpark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carpark?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - carpark

  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: carpark
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - carpark

volumes:
  db-data:

networks:
  carpark: