spring:
  main:
    bannerMode: off
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    group: true
    baseline-on-migrate: true

gov-sg:
  get-car-park-availability-url: https://api.data.gov.sg/v1/transport/carpark-availability
